//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PagoProfesores.srv_mySuiteTest {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.fact.com.mx/schema/ws", ConfigurationName="srv_mySuiteTest.FactWSFrontSoap")]
    public interface FactWSFrontSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/RequestTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PagoProfesores.srv_mySuiteTest.TransactionTag RequestTransaction(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/RequestTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<PagoProfesores.srv_mySuiteTest.TransactionTag> RequestTransactionAsync(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/SSLTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SSLTransaction(string Entity, string Transaction, string DataExchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/SSLTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SSLTransactionAsync(string Entity, string Transaction, string DataExchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/SecureTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SecureTransaction(string Entity, string Transaction, string DataExchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/SecureTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SecureTransactionAsync(string Entity, string Transaction, string DataExchange);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/MySuiteTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MySuiteTransaction(string Entity, string Transaction, string DataExchange, string PrivateData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/MySuiteTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<string> MySuiteTransactionAsync(string Entity, string Transaction, string DataExchange, string PrivateData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/ServiceCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        PagoProfesores.srv_mySuiteTest.ServiceCallResult ServiceCall(string rfc, string user, string tran, string pars, string additionalPars, string LastTimeStamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/ServiceCall", ReplyAction="*")]
        System.Threading.Tasks.Task<PagoProfesores.srv_mySuiteTest.ServiceCallResult> ServiceCallAsync(string rfc, string user, string tran, string pars, string additionalPars, string LastTimeStamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/Authenticate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Authenticate(string taxID, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/Authenticate", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AuthenticateAsync(string taxID, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/AuthenticateWTransform", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AuthenticateWTransform(string taxID, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/AuthenticateWTransform", ReplyAction="*")]
        System.Threading.Tasks.Task<string> AuthenticateWTransformAsync(string taxID, string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/JsonServiceCall", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string JsonServiceCall(string jsonData, string transactionName, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.fact.com.mx/schema/ws/JsonServiceCall", ReplyAction="*")]
        System.Threading.Tasks.Task<string> JsonServiceCallAsync(string jsonData, string transactionName, string token);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class TransactionTag : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FactRequest requestField;
        
        private FactResponse responseField;
        
        private FactResponseData responseDataField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FactRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
                this.RaisePropertyChanged("Request");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FactResponse Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
                this.RaisePropertyChanged("Response");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public FactResponseData ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
                this.RaisePropertyChanged("ResponseData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid requestorField;
        
        private string requestorNameField;
        
        private bool requestorActiveField;
        
        private Transactions transactionField;
        
        private string countryField;
        
        private string entityField;
        
        private System.Guid userField;
        
        private string userNameField;
        
        private System.Guid idField;
        
        private System.DateTime timeStampField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Requestor {
            get {
                return this.requestorField;
            }
            set {
                this.requestorField = value;
                this.RaisePropertyChanged("Requestor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequestorName {
            get {
                return this.requestorNameField;
            }
            set {
                this.requestorNameField = value;
                this.RaisePropertyChanged("RequestorName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool RequestorActive {
            get {
                return this.requestorActiveField;
            }
            set {
                this.requestorActiveField = value;
                this.RaisePropertyChanged("RequestorActive");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Transactions Transaction {
            get {
                return this.transactionField;
            }
            set {
                this.transactionField = value;
                this.RaisePropertyChanged("Transaction");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("Entity");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.Guid User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("User");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public enum Transactions {
        
        /// <comentarios/>
        BASE,
        
        /// <comentarios/>
        NO_TRANSACTION,
        
        /// <comentarios/>
        CONVERT_NATIVE_XML,
        
        /// <comentarios/>
        GET_MTE_BATCH,
        
        /// <comentarios/>
        PROCESS_BATCH,
        
        /// <comentarios/>
        SYSTEM_REQUEST,
        
        /// <comentarios/>
        RECEIVE_BATCH,
        
        /// <comentarios/>
        ENROLL_CERT,
        
        /// <comentarios/>
        GET_XML,
        
        /// <comentarios/>
        GET_HTML,
        
        /// <comentarios/>
        GET_XML_AND_HTML,
        
        /// <comentarios/>
        CANCEL_XML,
        
        /// <comentarios/>
        MARK_XML_AS_PAID,
        
        /// <comentarios/>
        MARK_XML_AS_UNPAID,
        
        /// <comentarios/>
        SEARCH_BASIC,
        
        /// <comentarios/>
        GET_MONTHLY_REPORT,
        
        /// <comentarios/>
        GET_MONTHLY_REPORT_FOR_PROVIDER,
        
        /// <comentarios/>
        GET_FOLIOS_BY_RFC,
        
        /// <comentarios/>
        DOES_ASSIGNMENT_EXIST,
        
        /// <comentarios/>
        CANCEL_XML_BY_INTERNAL_ID,
        
        /// <comentarios/>
        ACTIVATE_ASSIGNMENT,
        
        /// <comentarios/>
        COUNT_ACTIVE_ASSIGNMENTS,
        
        /// <comentarios/>
        GET_DOCUMENT,
        
        /// <comentarios/>
        GET_DOCUMENT_RETENCIONES,
        
        /// <comentarios/>
        AUTHENTICATE_USER,
        
        /// <comentarios/>
        GET_ACCOUNT,
        
        /// <comentarios/>
        DISTRIBUTE,
        
        /// <comentarios/>
        QUEUE_FOR_DISTRIBUTION,
        
        /// <comentarios/>
        GET_EFFECTIVE_RIGHTS,
        
        /// <comentarios/>
        EXEC_STORED_PROC,
        
        /// <comentarios/>
        GET_USER_INFO,
        
        /// <comentarios/>
        RECEIVE,
        
        /// <comentarios/>
        GET_PREVIEW,
        
        /// <comentarios/>
        RETRIEVE_DOCUMENT,
        
        /// <comentarios/>
        MARK_DOCUMENT_AS_PAID,
        
        /// <comentarios/>
        MARK_DOCUMENT_AS_NOT_PAID,
        
        /// <comentarios/>
        CANCEL_DOCUMENT,
        
        /// <comentarios/>
        MARK_DOCUMENT_AS_DELETED,
        
        /// <comentarios/>
        MARK_DOCUMENT_AS_NOT_DELETED,
        
        /// <comentarios/>
        MARK_DOCUMENT_AS_CANCELLED,
        
        /// <comentarios/>
        MARK_DOCUMENT_AS_NOT_CANCELLED,
        
        /// <comentarios/>
        GET_ADDENDA_RECEIVERS,
        
        /// <comentarios/>
        REQUEST_PASSWORD_CHANGE,
        
        /// <comentarios/>
        CHANGE_DOCUMENT_SUCURSAL,
        
        /// <comentarios/>
        CREATE_ACCOUNT_AS_OWNER,
        
        /// <comentarios/>
        CREATE_PASSWORD,
        
        /// <comentarios/>
        PASSWORD_FORGOT,
        
        /// <comentarios/>
        CREATE_USER,
        
        /// <comentarios/>
        INCREMENT_BUNDLE_SIZE,
        
        /// <comentarios/>
        TIMBRAR,
        
        /// <comentarios/>
        LOOKUP_ISSUED_INTERNAL_ID,
        
        /// <comentarios/>
        VALIDATE_CERT,
        
        /// <comentarios/>
        BATCH_SERIAL_OPERATIONS,
        
        /// <comentarios/>
        PROCESS_LCO,
        
        /// <comentarios/>
        ENROLL_THIRD_PARTY_CERT,
        
        /// <comentarios/>
        CANCEL_CFDI,
        
        /// <comentarios/>
        UPDATE_ACCOUNT_DATA,
        
        /// <comentarios/>
        ASSIGN_ACCOUNT_REQUESTOR,
        
        /// <comentarios/>
        UPDATE_USER_DATA,
        
        /// <comentarios/>
        UPDATE_ADMIN_USER_DATA,
        
        /// <comentarios/>
        CREATE_ADMIN_USER,
        
        /// <comentarios/>
        UPSERT_GRAPHIC_REPRESENTATION,
        
        /// <comentarios/>
        LOOKUP_ISSUED_BATCH_AND_SERIAL,
        
        /// <comentarios/>
        CREATE_TIMBRAR_ACCOUNT,
        
        /// <comentarios/>
        CREATE_TIMBRAR_ISSUER_ACCOUNT,
        
        /// <comentarios/>
        LOOKUP_GUATEMALIAN_ISSUED,
        
        /// <comentarios/>
        CLOSE_MONTH,
        
        /// <comentarios/>
        SYSTEM_REQUEST1,
        
        /// <comentarios/>
        GET_ACUSE,
        
        /// <comentarios/>
        GRAPH_REQUEST,
        
        /// <comentarios/>
        CANCEL_SINGLE_CFDI,
        
        /// <comentarios/>
        CONFIG_REFRESH,
        
        /// <comentarios/>
        GET_TIMBRAR_ACCOUNT,
        
        /// <comentarios/>
        GET_TIMBRAR_ISSUER_ACCOUNTS,
        
        /// <comentarios/>
        CONTRACT_ACCEPTANCE,
        
        /// <comentarios/>
        CREATE_FACT_RENEWAL,
        
        /// <comentarios/>
        CREATE_TIMB_RENEWAL,
        
        /// <comentarios/>
        DELETE_FACT_RENEWAL,
        
        /// <comentarios/>
        DELETE_TIMB_RENEWAL,
        
        /// <comentarios/>
        MODIFY_FACT_RENEWAL,
        
        /// <comentarios/>
        MODIFY_TIMB_RENEWAL,
        
        /// <comentarios/>
        RECOVER_FACT_RENEWAL,
        
        /// <comentarios/>
        RECOVER_TIMB_RENEWAL,
        
        /// <comentarios/>
        SELECT_FACT_RENEWAL,
        
        /// <comentarios/>
        SELECT_TIMB_RENEWAL,
        
        /// <comentarios/>
        PREINVOICE_SELECT,
        
        /// <comentarios/>
        PREINVOICE_DELETE,
        
        /// <comentarios/>
        PREINVOICE_UPSERT,
        
        /// <comentarios/>
        VALIDATE_DOCUMENT,
        
        /// <comentarios/>
        ACTIVATE_ACCOUNT,
        
        /// <comentarios/>
        INACTIVATE_ACCOUNT,
        
        /// <comentarios/>
        DELETE_ACCOUNT,
        
        /// <comentarios/>
        ACTIVATE_TIMBRAR_ACCOUNT,
        
        /// <comentarios/>
        INACTIVATE_TIMBRAR_ACCOUNT,
        
        /// <comentarios/>
        DELETE_TIMBRAR_ACCOUNT,
        
        /// <comentarios/>
        GET_ACCOUNTS_CHANGES,
        
        /// <comentarios/>
        GET_TIMBRAR_ACCOUNTS_CHANGES,
        
        /// <comentarios/>
        GET_ACCOUNTSSALES_CHANGES,
        
        /// <comentarios/>
        GET_TIMBRAR_ACCOUNTSSALES_CHANGES,
        
        /// <comentarios/>
        SET_PASS_POLICY,
        
        /// <comentarios/>
        RECEIVE_EX,
        
        /// <comentarios/>
        VALIDATE_DOCUMENT_EX,
        
        /// <comentarios/>
        RETRIEVE_OBSERVATIONS,
        
        /// <comentarios/>
        TIMBRAR_RETENCIONES,
        
        /// <comentarios/>
        TIMBRAR_RETENCION,
        
        /// <comentarios/>
        CANCEL_SINGLE_RETENCIONES,
        
        /// <comentarios/>
        CANCEL_SINGLE_RETENCION,
        
        /// <comentarios/>
        CANCELAR_RETENCION,
        
        /// <comentarios/>
        FIRMAR_RETENCION,
        
        /// <comentarios/>
        END_SESSION_LOG,
        
        /// <comentarios/>
        CANCELAR_RETENCION_MYSUITE,
        
        /// <comentarios/>
        CANCELAR_RETENCION_SINGLE_MYSUITE,
        
        /// <comentarios/>
        AUTHENTICATE,
        
        /// <comentarios/>
        GET_WEB_SCREEN_MAINFRAME,
        
        /// <comentarios/>
        GET_HOME_CONTENT,
        
        /// <comentarios/>
        OBTAIN_TEMPLATE,
        
        /// <comentarios/>
        GET_USER_CREDENTIALS_HTML,
        
        /// <comentarios/>
        OBTAIN_TEMPLATE_COUNT,
        
        /// <comentarios/>
        RETRIEVE_DOCUMENT_HTML,
        
        /// <comentarios/>
        GET_DOC_DETAILS,
        
        /// <comentarios/>
        CANCEL_XML_BATCH,
        
        /// <comentarios/>
        GET_REPORTS,
        
        /// <comentarios/>
        GET_REPORT_DATA,
        
        /// <comentarios/>
        EXECUTE_REPORT,
        
        /// <comentarios/>
        PAY_XML,
        
        /// <comentarios/>
        PAY_XML_BATCH,
        
        /// <comentarios/>
        REDISTRIBUTE,
        
        /// <comentarios/>
        GET_EXCEL_LIST,
        
        /// <comentarios/>
        OBTAIN_TEMPLATE_CONFIG,
        
        /// <comentarios/>
        OBTAIN_TEMPLATE_FOR_PAYMENT,
        
        /// <comentarios/>
        USER_FORGOT,
        
        /// <comentarios/>
        GET_CLIENT_LIST,
        
        /// <comentarios/>
        GET_CLIENT_COUNT,
        
        /// <comentarios/>
        GET_BRANCH_LIST,
        
        /// <comentarios/>
        GET_BRANCH_COUNT,
        
        /// <comentarios/>
        SEND_XML_MAIL,
        
        /// <comentarios/>
        GET_PAYMENTS,
        
        /// <comentarios/>
        DELETE_PAYMENT,
        
        /// <comentarios/>
        GET_FISCAL_DATA,
        
        /// <comentarios/>
        SAVE_TEMPLATE_CONFIG,
        
        /// <comentarios/>
        UPSERT_BANK_ACCOUNTS,
        
        /// <comentarios/>
        DELETE_BANK_ACCOUNTS,
        
        /// <comentarios/>
        GET_USER_CREDENTIALS,
        
        /// <comentarios/>
        UPSERT_BRANCH,
        
        /// <comentarios/>
        INSERT_FISCAL_R,
        
        /// <comentarios/>
        UPDATE_FISCAL_R,
        
        /// <comentarios/>
        REMOVE_FISCAL_R,
        
        /// <comentarios/>
        RETRIEVE_ALL_FISCAL_R,
        
        /// <comentarios/>
        UPSERT_CLIENT,
        
        /// <comentarios/>
        DELETE_CLIENT,
        
        /// <comentarios/>
        GET_DESTINATION_LIST,
        
        /// <comentarios/>
        GET_DESTINATION_COUNT,
        
        /// <comentarios/>
        UPSERT_DESTINATION,
        
        /// <comentarios/>
        UPSERT_FISCAL_DATA,
        
        /// <comentarios/>
        GET_EMPLOYEE_LIST,
        
        /// <comentarios/>
        GET_EMPLOYEE_COUNT,
        
        /// <comentarios/>
        UPSERT_EMPLOYEE,
        
        /// <comentarios/>
        DELETE_EMPLOYEE,
        
        /// <comentarios/>
        GET_ASSOCIATED_ACCOUNTS_LIST,
        
        /// <comentarios/>
        GET_ASSOCIATED_ACCOUNTS_COUNT,
        
        /// <comentarios/>
        SET_ACCOUNT_ACTIVE_STATUS,
        
        /// <comentarios/>
        GET_ACCOUNT_DATA,
        
        /// <comentarios/>
        GET_ACCOUNT_RENEW_INFO,
        
        /// <comentarios/>
        GET_ACCOUNT_SERIAL_INFO,
        
        /// <comentarios/>
        GET_ACCOUNT_CERT_INFO,
        
        /// <comentarios/>
        GET_ACCOUNT_USER_LIST,
        
        /// <comentarios/>
        GET_ACCOUNT_USER_COUNT,
        
        /// <comentarios/>
        GET_ACCOUNT_BRANCH_ASSIGNMENT_LIST,
        
        /// <comentarios/>
        GET_ACCOUNT_BRANCH_ASSIGNMENT_COUNT,
        
        /// <comentarios/>
        GET_ACCOUNT_BY_OWNER,
        
        /// <comentarios/>
        CREATE_ACCOUNT,
        
        /// <comentarios/>
        GET_CLIENT_LIST_AUTOCOMPLETE,
        
        /// <comentarios/>
        GET_BRANCH_LIST_AUTOCOMPLETE,
        
        /// <comentarios/>
        GET_DESTINATION_LIST_AUTOCOMPLETE,
        
        /// <comentarios/>
        GET_CLIENT_BY_ID,
        
        /// <comentarios/>
        GET_BRANCH_BY_ID,
        
        /// <comentarios/>
        GET_DESTINATION_BY_ID,
        
        /// <comentarios/>
        GET_PRODUCT_LIST,
        
        /// <comentarios/>
        GET_PRODUCT_COUNT,
        
        /// <comentarios/>
        GET_PRODUCT_LIST_AUTOCOMPLETE,
        
        /// <comentarios/>
        GET_PRODUCT_BY_ID,
        
        /// <comentarios/>
        DELETE_PRODUCT,
        
        /// <comentarios/>
        UPSERT_PRODUCT,
        
        /// <comentarios/>
        CHANGE_USER_PASSWORD,
        
        /// <comentarios/>
        GET_FACTS,
        
        /// <comentarios/>
        GET_FACTS_COUNT,
        
        /// <comentarios/>
        RETRIEVE_BANK_ACCOUNT,
        
        /// <comentarios/>
        AMOUNT_TO_STRING,
        
        /// <comentarios/>
        MARK_DOCUMENTS_AS_READ,
        
        /// <comentarios/>
        GET_UNREAD_COUNT,
        
        /// <comentarios/>
        GET_PAYMENTS_JSON,
        
        /// <comentarios/>
        CONVERT_NATIVE_XML_HTML,
        
        /// <comentarios/>
        MARK_DOCUMENTS_AS_READ_HTML,
        
        /// <comentarios/>
        GET_UNREAD_COUNT_HTML,
        
        /// <comentarios/>
        GET_ACUSE_RETENCIONES,
        
        /// <comentarios/>
        CANCEL_XML_HTML,
        
        /// <comentarios/>
        GET_ACCOUNT_INFO,
        
        /// <comentarios/>
        PROCESA_FACTURAS,
        
        /// <comentarios/>
        PROCESA_NOMINA,
        
        /// <comentarios/>
        DOCUMENT_ZIP,
        
        /// <comentarios/>
        AUTHENTICATE_FIEL,
        
        /// <comentarios/>
        UPDATE_ACCOUNT_OWNER,
        
        /// <comentarios/>
        GET_REQUEST_QUEUE,
        
        /// <comentarios/>
        CREATE_REQUEST_QUEUE,
        
        /// <comentarios/>
        UPDATE_REQUEST_QUEUE,
        
        /// <comentarios/>
        PROCESS_REQUEST_QUEUE,
        
        /// <comentarios/>
        DELETE_REQUEST_QUEUE,
        
        /// <comentarios/>
        GET_LINK_QUEUE,
        
        /// <comentarios/>
        GET_REQUEST_QUEUE_COUNT,
        
        /// <comentarios/>
        GET_CATALOG_LIST_AUTOCOMPLETE,
        
        /// <comentarios/>
        GET_CATALOG_By_ID,
        
        /// <comentarios/>
        FIRMAR_CONTRATO,
        
        /// <comentarios/>
        VALIDAR_COMPLEMENTO,
        
        /// <comentarios/>
        GET_TAXID_LIST_AUTOCOMPLETE,
        
        /// <comentarios/>
        GET_CLAVEPRODSERV_LIST_AUTOCOMPLETE,
        
        /// <comentarios/>
        GET_CLAVEPRODSERV_BY_ID,
        
        /// <comentarios/>
        GET_CLAVEUNIDAD_LIST_AUTOCOMPLETE,
        
        /// <comentarios/>
        GET_CLAVEUNIDAD_BY_ID,
        
        /// <comentarios/>
        SOLICITAR_CONFIRMACION,
        
        /// <comentarios/>
        GET_PREINVOICES_BY_ID,
        
        /// <comentarios/>
        RECUPERAR_CLAVE_CONFIRMACION,
        
        /// <comentarios/>
        GET_PREVIEW_HTML,
        
        /// <comentarios/>
        RETRIEVE_DOCUMENT_HTML_FORMATS,
        
        /// <comentarios/>
        LOOKUP_ISSUED_INTERNAL_ID_HTML,
        
        /// <comentarios/>
        PREINVOICE_UPSERT_HTML,
        
        /// <comentarios/>
        GET_ACUSE_CANCEL,
        
        /// <comentarios/>
        RETRIEVE_LCO_INFO,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class ServiceCallResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentResultField;
        
        private bool resultField;
        
        private string errorMsgField;
        
        private string errorCodeField;
        
        private string lastTimeStampField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContentResult {
            get {
                return this.contentResultField;
            }
            set {
                this.contentResultField = value;
                this.RaisePropertyChanged("ContentResult");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("ErrorMsg");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LastTimeStamp {
            get {
                return this.lastTimeStampField;
            }
            set {
                this.lastTimeStampField = value;
                this.RaisePropertyChanged("LastTimeStamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactResponseData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responseData1Field;
        
        private string responseData2Field;
        
        private string responseData3Field;
        
        private System.Data.DataSet responseDataSetField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ResponseData1 {
            get {
                return this.responseData1Field;
            }
            set {
                this.responseData1Field = value;
                this.RaisePropertyChanged("ResponseData1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResponseData2 {
            get {
                return this.responseData2Field;
            }
            set {
                this.responseData2Field = value;
                this.RaisePropertyChanged("ResponseData2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ResponseData3 {
            get {
                return this.responseData3Field;
            }
            set {
                this.responseData3Field = value;
                this.RaisePropertyChanged("ResponseData3");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Data.DataSet ResponseDataSet {
            get {
                return this.responseDataSetField;
            }
            set {
                this.responseDataSetField = value;
                this.RaisePropertyChanged("ResponseDataSet");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class BatchID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string batchIdField;
        
        private string batchTimeStampField;
        
        private string batchRequestorCountryField;
        
        private string batchRequestorEntityField;
        
        private string batchPositionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BatchId {
            get {
                return this.batchIdField;
            }
            set {
                this.batchIdField = value;
                this.RaisePropertyChanged("BatchId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BatchTimeStamp {
            get {
                return this.batchTimeStampField;
            }
            set {
                this.batchTimeStampField = value;
                this.RaisePropertyChanged("BatchTimeStamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BatchRequestorCountry {
            get {
                return this.batchRequestorCountryField;
            }
            set {
                this.batchRequestorCountryField = value;
                this.RaisePropertyChanged("BatchRequestorCountry");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BatchRequestorEntity {
            get {
                return this.batchRequestorEntityField;
            }
            set {
                this.batchRequestorEntityField = value;
                this.RaisePropertyChanged("BatchRequestorEntity");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BatchPosition {
            get {
                return this.batchPositionField;
            }
            set {
                this.batchPositionField = value;
                this.RaisePropertyChanged("BatchPosition");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class DocID : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string entityField;
        
        private string fiscalNameField;
        
        private string aYearField;
        
        private string aNumberField;
        
        private string batchField;
        
        private string serialField;
        
        private string documentGUIDField;
        
        private string issuedTimeStampField;
        
        private string enrolledTimeStampField;
        
        private string paidTimeStampField;
        
        private string cancelledTimeStampField;
        
        private string internalIDField;
        
        private string batchIDField;
        
        private string batchTimeStampField;
        
        private string batchRequestorCountryField;
        
        private string batchRequestorEntityField;
        
        private string batchPositionField;
        
        private string receiverCountryField;
        
        private string receiverEntityField;
        
        private string receiverTaxIDField;
        
        private string receiverNameField;
        
        private string claveAgenteField;
        
        private string numeroDePolizaField;
        
        private string currencyField;
        
        private string totalAmountField;
        
        private string type1Field;
        
        private string type2Field;
        
        private string suggestedFileNameField;
        
        private string suggestedFileName2Field;
        
        private string observacionesField;
        
        private string observacionesHtmlField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("Country");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("Entity");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FiscalName {
            get {
                return this.fiscalNameField;
            }
            set {
                this.fiscalNameField = value;
                this.RaisePropertyChanged("FiscalName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AYear {
            get {
                return this.aYearField;
            }
            set {
                this.aYearField = value;
                this.RaisePropertyChanged("AYear");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ANumber {
            get {
                return this.aNumberField;
            }
            set {
                this.aNumberField = value;
                this.RaisePropertyChanged("ANumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
                this.RaisePropertyChanged("Batch");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
                this.RaisePropertyChanged("Serial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DocumentGUID {
            get {
                return this.documentGUIDField;
            }
            set {
                this.documentGUIDField = value;
                this.RaisePropertyChanged("DocumentGUID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IssuedTimeStamp {
            get {
                return this.issuedTimeStampField;
            }
            set {
                this.issuedTimeStampField = value;
                this.RaisePropertyChanged("IssuedTimeStamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string EnrolledTimeStamp {
            get {
                return this.enrolledTimeStampField;
            }
            set {
                this.enrolledTimeStampField = value;
                this.RaisePropertyChanged("EnrolledTimeStamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string PaidTimeStamp {
            get {
                return this.paidTimeStampField;
            }
            set {
                this.paidTimeStampField = value;
                this.RaisePropertyChanged("PaidTimeStamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CancelledTimeStamp {
            get {
                return this.cancelledTimeStampField;
            }
            set {
                this.cancelledTimeStampField = value;
                this.RaisePropertyChanged("CancelledTimeStamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string InternalID {
            get {
                return this.internalIDField;
            }
            set {
                this.internalIDField = value;
                this.RaisePropertyChanged("InternalID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string BatchID {
            get {
                return this.batchIDField;
            }
            set {
                this.batchIDField = value;
                this.RaisePropertyChanged("BatchID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string BatchTimeStamp {
            get {
                return this.batchTimeStampField;
            }
            set {
                this.batchTimeStampField = value;
                this.RaisePropertyChanged("BatchTimeStamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string BatchRequestorCountry {
            get {
                return this.batchRequestorCountryField;
            }
            set {
                this.batchRequestorCountryField = value;
                this.RaisePropertyChanged("BatchRequestorCountry");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string BatchRequestorEntity {
            get {
                return this.batchRequestorEntityField;
            }
            set {
                this.batchRequestorEntityField = value;
                this.RaisePropertyChanged("BatchRequestorEntity");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string BatchPosition {
            get {
                return this.batchPositionField;
            }
            set {
                this.batchPositionField = value;
                this.RaisePropertyChanged("BatchPosition");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ReceiverCountry {
            get {
                return this.receiverCountryField;
            }
            set {
                this.receiverCountryField = value;
                this.RaisePropertyChanged("ReceiverCountry");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ReceiverEntity {
            get {
                return this.receiverEntityField;
            }
            set {
                this.receiverEntityField = value;
                this.RaisePropertyChanged("ReceiverEntity");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ReceiverTaxID {
            get {
                return this.receiverTaxIDField;
            }
            set {
                this.receiverTaxIDField = value;
                this.RaisePropertyChanged("ReceiverTaxID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ReceiverName {
            get {
                return this.receiverNameField;
            }
            set {
                this.receiverNameField = value;
                this.RaisePropertyChanged("ReceiverName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ClaveAgente {
            get {
                return this.claveAgenteField;
            }
            set {
                this.claveAgenteField = value;
                this.RaisePropertyChanged("ClaveAgente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string NumeroDePoliza {
            get {
                return this.numeroDePolizaField;
            }
            set {
                this.numeroDePolizaField = value;
                this.RaisePropertyChanged("NumeroDePoliza");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
                this.RaisePropertyChanged("TotalAmount");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Type1 {
            get {
                return this.type1Field;
            }
            set {
                this.type1Field = value;
                this.RaisePropertyChanged("Type1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string Type2 {
            get {
                return this.type2Field;
            }
            set {
                this.type2Field = value;
                this.RaisePropertyChanged("Type2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string SuggestedFileName {
            get {
                return this.suggestedFileNameField;
            }
            set {
                this.suggestedFileNameField = value;
                this.RaisePropertyChanged("SuggestedFileName");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string SuggestedFileName2 {
            get {
                return this.suggestedFileName2Field;
            }
            set {
                this.suggestedFileName2Field = value;
                this.RaisePropertyChanged("SuggestedFileName2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
                this.RaisePropertyChanged("Observaciones");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string ObservacionesHtml {
            get {
                return this.observacionesHtmlField;
            }
            set {
                this.observacionesHtmlField = value;
                this.RaisePropertyChanged("ObservacionesHtml");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool resultField;
        
        private System.DateTime timeStampField;
        
        private string lastResultField;
        
        private int codeField;
        
        private string descriptionField;
        
        private string hintField;
        
        private string dataField;
        
        private string processorField;
        
        private DocID identifierField;
        
        private BatchID batchIdentifierField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
                this.RaisePropertyChanged("TimeStamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastResult {
            get {
                return this.lastResultField;
            }
            set {
                this.lastResultField = value;
                this.RaisePropertyChanged("LastResult");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Hint {
            get {
                return this.hintField;
            }
            set {
                this.hintField = value;
                this.RaisePropertyChanged("Hint");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Processor {
            get {
                return this.processorField;
            }
            set {
                this.processorField = value;
                this.RaisePropertyChanged("Processor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public DocID Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
                this.RaisePropertyChanged("Identifier");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public BatchID BatchIdentifier {
            get {
                return this.batchIdentifierField;
            }
            set {
                this.batchIdentifierField = value;
                this.RaisePropertyChanged("BatchIdentifier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FactWSFrontSoapChannel : PagoProfesores.srv_mySuiteTest.FactWSFrontSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FactWSFrontSoapClient : System.ServiceModel.ClientBase<PagoProfesores.srv_mySuiteTest.FactWSFrontSoap>, PagoProfesores.srv_mySuiteTest.FactWSFrontSoap {
        
        public FactWSFrontSoapClient() {
        }
        
        public FactWSFrontSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FactWSFrontSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FactWSFrontSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FactWSFrontSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PagoProfesores.srv_mySuiteTest.TransactionTag RequestTransaction(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3) {
            return base.Channel.RequestTransaction(Requestor, Transaction, Country, Entity, User, UserName, Data1, Data2, Data3);
        }
        
        public System.Threading.Tasks.Task<PagoProfesores.srv_mySuiteTest.TransactionTag> RequestTransactionAsync(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3) {
            return base.Channel.RequestTransactionAsync(Requestor, Transaction, Country, Entity, User, UserName, Data1, Data2, Data3);
        }
        
        public string SSLTransaction(string Entity, string Transaction, string DataExchange) {
            return base.Channel.SSLTransaction(Entity, Transaction, DataExchange);
        }
        
        public System.Threading.Tasks.Task<string> SSLTransactionAsync(string Entity, string Transaction, string DataExchange) {
            return base.Channel.SSLTransactionAsync(Entity, Transaction, DataExchange);
        }
        
        public string SecureTransaction(string Entity, string Transaction, string DataExchange) {
            return base.Channel.SecureTransaction(Entity, Transaction, DataExchange);
        }
        
        public System.Threading.Tasks.Task<string> SecureTransactionAsync(string Entity, string Transaction, string DataExchange) {
            return base.Channel.SecureTransactionAsync(Entity, Transaction, DataExchange);
        }
        
        public string MySuiteTransaction(string Entity, string Transaction, string DataExchange, string PrivateData) {
            return base.Channel.MySuiteTransaction(Entity, Transaction, DataExchange, PrivateData);
        }
        
        public System.Threading.Tasks.Task<string> MySuiteTransactionAsync(string Entity, string Transaction, string DataExchange, string PrivateData) {
            return base.Channel.MySuiteTransactionAsync(Entity, Transaction, DataExchange, PrivateData);
        }
        
        public PagoProfesores.srv_mySuiteTest.ServiceCallResult ServiceCall(string rfc, string user, string tran, string pars, string additionalPars, string LastTimeStamp) {
            return base.Channel.ServiceCall(rfc, user, tran, pars, additionalPars, LastTimeStamp);
        }
        
        public System.Threading.Tasks.Task<PagoProfesores.srv_mySuiteTest.ServiceCallResult> ServiceCallAsync(string rfc, string user, string tran, string pars, string additionalPars, string LastTimeStamp) {
            return base.Channel.ServiceCallAsync(rfc, user, tran, pars, additionalPars, LastTimeStamp);
        }
        
        public string Authenticate(string taxID, string user, string pass) {
            return base.Channel.Authenticate(taxID, user, pass);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateAsync(string taxID, string user, string pass) {
            return base.Channel.AuthenticateAsync(taxID, user, pass);
        }
        
        public string AuthenticateWTransform(string taxID, string user, string pass) {
            return base.Channel.AuthenticateWTransform(taxID, user, pass);
        }
        
        public System.Threading.Tasks.Task<string> AuthenticateWTransformAsync(string taxID, string user, string pass) {
            return base.Channel.AuthenticateWTransformAsync(taxID, user, pass);
        }
        
        public string JsonServiceCall(string jsonData, string transactionName, string token) {
            return base.Channel.JsonServiceCall(jsonData, transactionName, token);
        }
        
        public System.Threading.Tasks.Task<string> JsonServiceCallAsync(string jsonData, string transactionName, string token) {
            return base.Channel.JsonServiceCallAsync(jsonData, transactionName, token);
        }
    }
}
